Class Code - Fateme Rahimi

1.1 Creating a Vector

In [25]:
# Load library
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column
vector_column = np.array([[1],
                          [2],
                          [3]])

1.2 Creating a Matrix

In [6]:
vector_row

array([1, 2, 3])

In [7]:
# Load library
import numpy as np

# Create a matrix
matrix = np.array([[1, 2],
                   [1, 2],
                   [1, 2]])

In [8]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

1.3 Creating a Sparse Matrix

In [9]:
# Load libraries
import numpy as np
from scipy import sparse

# Create a matrix
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])

# Create compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [10]:
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


In [11]:
# Create larger matrix
matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)

In [12]:
# View larger sparse matrix
print(matrix_large_sparse)

  (1, 1)	1
  (2, 0)	3


1.4 Selecting Elements

In [13]:
# Load library
import numpy as np

# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Select third element of vector
vector[2]

3

In [14]:
# Select all elements of a vector
vector[:]

array([1, 2, 3, 4, 5, 6])

In [15]:
# Select everything up to and including the third element
vector[:3]

array([1, 2, 3])

In [16]:
# Select everything after the third element
vector[3:]

array([4, 5, 6])

In [17]:
# Select the last element
vector[-1]

6

In [18]:
# Select the first two rows and all columns of a matrix
matrix[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
# Select all rows and the second column
matrix[:,1:2]

array([[2],
       [5],
       [8]])

1.5 Describing a Matrix

In [20]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

# View number of rows and columns
matrix.shape

(3, 4)

In [21]:
# View number of elements (rows * columns)
matrix.size

12

In [22]:
# View number of dimensions
matrix.ndim

2

1.6 Applying Operations to Elements

In [23]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Create function that adds 100 to something
add_100 = lambda i: i + 100

# Create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Apply function to all elements in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [24]:
# Add 100 to all elements
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

1.7 Finding the Maximum and Minimum Values

In [26]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return maximum element
np.max(matrix)

9

In [27]:
# Return minimum element
np.min(matrix)

1

In [28]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [29]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

1.8 Calculating the Average, Variance, and Standard Deviation

In [30]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Return mean
np.mean(matrix)

5.0

In [31]:
# Return variance
np.var(matrix)

6.666666666666667

In [32]:
# Return standard deviation
np.std(matrix)

2.581988897471611

In [33]:
# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

1.9 Reshaping Arrays

In [34]:
# Load library
import numpy as np

# Create 4x3 matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [35]:
matrix.size

12

In [36]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [38]:
matrix.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [39]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

1.10 Transposing a Vector or Matrix

In [40]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Transpose matrix
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [41]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

1.11 Flattening a Matrix

In [42]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flatten matrix
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

1.12 Finding the Rank of a Matrix

In [44]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

2

In [46]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]],
                   [[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]]])

# Return matrix rank
np.linalg.matrix_rank(matrix)

array([2, 2], dtype=int64)

1.13 Calculating the Determinant

In [47]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return determinant of matrix
np.linalg.det(matrix)

0.0

1.14 Getting the Diagonal of a Matrix

In [48]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return diagonal elements
matrix.diagonal()

array([1, 4, 9])

In [49]:
# Return diagonal one above the main diagonal
matrix.diagonal(offset=1)

array([2, 6])

In [50]:
# Return diagonal one below the main diagonal
matrix.diagonal(offset=-1)

array([2, 8])

1.15 Calculating the Trace of a Matrix

In [54]:
# Load library
import numpy as np

# Create matrix
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

# Return trace
matrix.trace()

14

In [55]:
# Return diagonal and sum elements
sum(matrix.diagonal())

14

1.16 Finding Eigenvalues and Eigenvectors

1.17 Calculating Dot Products

In [56]:
# Load library
import numpy as np

# Create two vectors
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

# Calculate dot product
np.dot(vector_a, vector_b)

32

In [57]:
# Calculate dot product
vector_a @ vector_b

32

1.18 Adding and Subtracting Matrices

In [58]:
# Load library
import numpy as np

# Create matrix
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

# Create matrix
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

# Add two matrices
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [59]:
# Subtract two matrices
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [62]:
# Add two matrices
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

1.19 Multiplying Matrices